import { BorderOptions } from "../BorderOptions";
import { Vector2D } from "../Vector2D";
import { UiObject } from "./UiObject";

/**
 * A Panel is a UI object that is used to display information to the user.
 */
export class Panel extends UiObject {
  #width: number;
  #height: number;
  #color: string | CanvasGradient | CanvasPattern;
  #borderOptions: BorderOptions;

  constructor(
    position: Vector2D,
    fixed: boolean,
    width: number,
    height: number,
    color: string | CanvasGradient | CanvasPattern,
    borderOptions: BorderOptions
  ) {
    super(position, fixed);
    this.#width = width;
    this.#height = height;
    this.#color = color;
    this.#borderOptions = borderOptions;
  }

  /**
   * Renders the panel to the screen.
   * @param ctx the canvas rendering context to render to.
   * !!! Mostly generated by Github Copilot !!!
   */
  override render(ctx: CanvasRenderingContext2D) {
    ctx.fillStyle = this.#color;
    ctx.strokeStyle = this.#borderOptions.color;
    ctx.lineWidth = this.#borderOptions.width;
    ctx.beginPath();
    ctx.moveTo(
      this.globalPosition.x + this.#borderOptions.radius,
      this.globalPosition.y
    );
    ctx.lineTo(
      this.globalPosition.x + this.#width - this.#borderOptions.radius,
      this.globalPosition.y
    );
    ctx.quadraticCurveTo(
      this.globalPosition.x + this.#width,
      this.globalPosition.y,
      this.globalPosition.x + this.#width,
      this.globalPosition.y + this.#borderOptions.radius
    );
    ctx.lineTo(
      this.globalPosition.x + this.#width,
      this.globalPosition.y + this.#height - this.#borderOptions.radius
    );
    ctx.quadraticCurveTo(
      this.globalPosition.x + this.#width,
      this.globalPosition.y + this.#height,
      this.globalPosition.x + this.#width - this.#borderOptions.radius,
      this.globalPosition.y + this.#height
    );
    ctx.lineTo(
      this.globalPosition.x + this.#borderOptions.radius,
      this.globalPosition.y + this.#height
    );
    ctx.quadraticCurveTo(
      this.globalPosition.x,
      this.globalPosition.y + this.#height,
      this.globalPosition.x,
      this.globalPosition.y + this.#height - this.#borderOptions.radius
    );
    ctx.lineTo(
      this.globalPosition.x,
      this.globalPosition.y + this.#borderOptions.radius
    );
    ctx.quadraticCurveTo(
      this.globalPosition.x,
      this.globalPosition.y,
      this.globalPosition.x + this.#borderOptions.radius,
      this.globalPosition.y
    );
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
  }
}
